#!/bin/bash
xrandr --output HDMI-1-2 --auto 
xrandr --output HDMI-1-2 --right-of eDP-1-1
xrandr --output HDMI-1-2 --mode 1680x1050 > /dev/null 2>&1
i3-msg restart
pactl set-card-profile 0 output:hdmi-stereo-extra1
pulseaudio -k
